fix: copy instead of move, also add update_frontmatter function
> now, the markdown files we are moving have a frontmatter section with metadata. I would like to rename the `date` property in this section to `pubDate`

> can this update of the frontmatter section be done in a separate function? Or how can we better organize the code?

> and I just realized that we are moving the source files instead of just copying them, which is less destructive and allows easier testing of the script :-p

> I did had to change this line `post['pubDate'] = post.pop('date')` to `post['pubDate'] = post.metadata.pop('date')` instead, because I had a `AttributeError: 'Post' object has no attribute 'pop'` error.